### PR TITLE
Add forms

### PR DESCRIPTION
**Pull request by PolinaStamenova**
# Add forms 

**Controllers:**
- Add   _#new and #create to PostsController_ that creates a new post.
- Add _CommentsController with #create_ that creates a new comment to a existing post using #current_user from the ApplicationController as logged-in user.
  - Incrementing the counter is happening in the model using _after_save_ rails method.
- Add _LikesController with #create_ that creates a new like on a existing post using #current_user from the ApplicationController as logged-in user.
  - Incrementing the counter is happening in the model using _after_save_ rails method.
  
**Views:**
- Create  "comments/_form.html.erb" file containing the form to create new comment. 
- Create  "likes/_form.html.erb" file containing the form to create new like. 

**Style:**
- Add basic style to:
 - comment section 
 - like section (button)

### Usage:  
- run `rails db:seed` to create the database.

_Thank you for taking time to review my PR!_ 😃 🌵

### CODE REVIEW

**Review by sinansevgi — COMMENTED** [review]
Hi @PolinaStamenova, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme file.

Documenting your code is one of the core skills you need to learn as a junior developer. And The microverse projects are a really great place to test your skills and get feedback on them. I recommend that you document all your projects properly. Please add a descriptive readme file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by PolinaStamenova** [comment]
Hi, @sinansevgi 
thank you for your remark!

**Review by sinansevgi — APPROVED** [review]
# Approved :heavy_check_mark: 

Hi @PolinaStamenova, 

All forms work fine  :+1: 
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sinansevgi** [comment]
[Optional]
- [ ] You should not commit your database username and password to a public repository. Please be sure you removed them before committing your code (Or you can use environment variables.)

**Pull request merged**
